// Breakpoints are generated by Style Dictionary (build:tokens) into src/breakpoints.ts
// This barrel is compiled by tsup into dist/index.js and dist/index.cjs
// DO NOT hand-edit src/breakpoints.ts — it is auto-generated
export * from './breakpoints';
